server:
  port: 0

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:{randome.value}}}
  client:
    registry-fetch-interval-seconds: 5